# Pair Numpy

In [1]:
import numpy as np

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.


In [ ]:
array_1d = np.random.randint(10, 99, 50)

In [5]:
array_1d

array([24, 45, 60, 32, 25, 24, 72, 95, 73, 63, 46, 90, 62, 66, 40, 43, 83,
       71, 50, 71, 76, 45, 88, 92, 63, 80, 45, 12, 63, 17, 61, 96, 16, 50,
       39, 33, 90, 85, 37, 75, 43, 44, 54, 78, 51, 20, 53, 76, 79, 70])

In [4]:
len(array_1d)

50

In [6]:
array_1d.size

50

In [7]:
array_1d[5]

np.int64(24)

In [8]:
array_1d[10]

np.int64(46)

In [11]:
array_1d[0::5]

array([24, 24, 46, 43, 76, 80, 61, 33, 43, 20])

2. Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.


In [ ]:
array_1d_1 = np.random.randint(1, 21, 30)
array_1d_1

array([ 4, 10, 19,  4,  4, 15,  8, 17, 12,  9,  3, 14,  2,  5,  8,  4, 10,
        1,  3, 16,  3, 18, 12,  5, 10,  7,  6, 15,  1, 13])

In [13]:
array_1d_1.size

30

In [16]:
array_1d_1[1::2]

array([10,  4, 15, 17,  9, 14,  5,  4,  1, 16, 18,  5,  7, 15, 13])

In [17]:
array_1d_1.shape

(30,)

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.


In [ ]:
array_2d = np.random.rand(4,6)

In [21]:
array_2d

array([[0.02517095, 0.05507287, 0.23393815, 0.28399817, 0.71894378,
        0.95134591],
       [0.10568161, 0.97675494, 0.16250056, 0.91923545, 0.93262163,
        0.89512814],
       [0.29177353, 0.35864599, 0.73256931, 0.38467993, 0.93633691,
        0.84200265],
       [0.81703896, 0.41890284, 0.37959654, 0.42515116, 0.42227988,
        0.374197  ]])

In [ ]:
array_2d[-1] #es lo mismo que array_2d[3]

array([0.81703896, 0.41890284, 0.37959654, 0.42515116, 0.42227988,
       0.374197  ])

In [25]:
# np.round(array, num_decimales_redondeo)
np.round(array_2d[-1],2)


array([0.82, 0.42, 0.38, 0.43, 0.42, 0.37])

# 2. Funciones Aritméticas y Estadísticas:
1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.


In [ ]:
array_3d = np.random.rand(2,3,5)
np.round((array_3d), 1)

array([[[0.7, 0.4, 0.2, 0.5, 0.7],
        [0.7, 0.9, 0.4, 0.2, 0. ],
        [1. , 0.6, 0.3, 0.6, 0.3]],

       [[0.4, 0.5, 0.1, 0.3, 0.3],
        [0.1, 0.5, 0.5, 0.6, 0.8],
        [0.7, 0.1, 0.8, 0.9, 0.4]]])

In [28]:
array_3d_1 = np.round((np.random.rand(2,3,5)),1)
array_3d_1

array([[[1. , 0.7, 0.6, 1. , 0.6],
        [0.3, 1. , 0.5, 1. , 0.6],
        [0.3, 0.6, 0.8, 0.8, 0.1]],

       [[0.5, 0.2, 0.8, 0.4, 0.7],
        [0.3, 0.3, 0.8, 0.3, 0.2],
        [0.1, 0.5, 0.4, 0.5, 0.4]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E

In [ ]:

array_vacio = np.empty((2, 3, 5))
array_vacio


array([[[1. , 0.7, 0.6, 1. , 0.6],
        [0.3, 1. , 0.5, 1. , 0.6],
        [0.3, 0.6, 0.8, 0.8, 0.1]],

       [[0.5, 0.2, 0.8, 0.4, 0.7],
        [0.3, 0.3, 0.8, 0.3, 0.2],
        [0.1, 0.5, 0.4, 0.5, 0.4]]])

In [32]:
media = np.round((np.mean(array_vacio)),1)
media

np.float64(0.5)

In [ ]:
#creación de la máscara lo almacenamos en variable (mascara_media)
mascara_media = array_vacio == media

In [ ]:
array_vacio == media #imprimir la máscara

array([[[False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False]],

       [[ True, False, False, False, False],
        [False, False, False, False, False],
        [False,  True, False,  True, False]]])

In [ ]:
mascara_media #imprimir la máscara

array([[[False, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False, False]],

       [[ True, False, False, False, False],
        [False, False, False, False, False],
        [False,  True, False,  True, False]]])

In [ ]:
array_vacio[mascara_media] #traeme los elementos True de la mascara

array([0.5, 0.5, 0.5, 0.5])

In [38]:
np.where(mascara_media, "A", " ")

array([[[' ', ' ', ' ', ' ', ' '],
        [' ', ' ', 'A', ' ', ' '],
        [' ', ' ', ' ', ' ', ' ']],

       [['A', ' ', ' ', ' ', ' '],
        [' ', ' ', ' ', ' ', ' '],
        [' ', 'A', ' ', 'A', ' ']]], dtype='<U1')